name = "portfolio"
compatibility_date = "2025-07-08"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]  
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".vercel/output/static"
